# ServerSync Plugin by AkramL
# Synchronize your spigot servers with proxies and manage them dynamically without extra configuration.

# A message broker is like a post office for computer programs, helping to send and receive messages to each other.
# It is important in this project to help with synchronizing servers between them.
# Available messages brokers for now:
# - REDIS
# - RABBITMQ (Not ready yet)
message-broker-service = "REDIS"
# The delay of repeating heartbeat check task in seconds (for proxies only!)
heartbeat-scheduler-delay = 15
# the maximum KeepAlive time to unregister the server in seconds (for proxies only!)
max-alive-time = 30
# How many seconds between each heartbeat? (For spigot)
heartbeat-interval = 5

# Here, you can configure important values to use redis as a message broker.
# Ignore it if you are using RABBITMQ.
[redis]
# Credentials values.
host = "0.0.0.0"
port = 6379
password = "password-here"
timeout = 5000 # In milliseconds.
# Pool configuration values.
max-total = 1
max-idle = 1
min-idle = 1
block-when-exhausted = false
min-evictable-idle-time = 60000
time-between-eviction-runs = 30000